theme: minima
title: Alex Pre-Med
email: your-email@example.com
description: >
  A high school student's journey to medicine.
baseurl: ""
url: "https://yourusername.github.io"
github_username: yourusername
